import * as THREE from 'three';
import {LineBatch} from './engine/lines.js';
import {TypeLayer,fonts} from './engine/type.js';
import {Post} from './engine/post.js?v=14';
import {loadMedia,seekVideo,ImageLayer} from './engine/media.js';
import {createDirector} from './plates/director.js?v=14';
import {shotNames,boundaries,shot,beat,ease,DURATION,SONG_OFFSET} from './timeline.js?v=14';
const renderer=new THREE.WebGLRenderer({antialias:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(1);renderer.setSize(1280,720,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.autoClear=false;document.querySelector('#viewer').append(renderer.domElement);
const lines=new LineBatch(26000,true),footerLines=new LineBatch(6500,true),footerType=new TypeLayer(),world=new LineBatch(26000,false),type=new TypeLayer(),images=new ImageLayer(),post=new Post(renderer,1280,720),camera=new THREE.PerspectiveCamera(45,16/9,.1,500),ortho=new THREE.OrthographicCamera(0,1920,1080,0,-10,10);
let width=1280,height=720,draw,music,media,current=0,playing=false,initialized=false,error=null,queue=Promise.resolve(),frame=0,renderedFrames=0,lastRenderMs=0,startWall=0,startFilm=0;
const score=document.querySelector('#score'),status=document.querySelector('#export-status'),play=document.querySelector('#play'),seek=document.querySelector('#seek'),select=document.querySelector('#shots');
seek.max=DURATION;document.querySelector('#time').textContent='00:00 / '+format(DURATION);
const ready=(async()=>{await fonts();music=await (await fetch('./data/music.json')).json();media=await loadMedia();const epochResponse=await fetch('./data/epochs.json');if(!epochResponse.ok)throw Error('Brand epoch data unavailable');const epochs=await epochResponse.json();draw=await createDirector(media,epochs);await paint(Number(new URLSearchParams(location.search).get('t'))||0);initialized=true;status.textContent='Ready · v14 · 85 seconds · A signal becomes a commons';})();ready.catch(e=>{error=e.message;status.textContent='Initialization failed: '+error;console.error(e)});
async function paint(t){let began=performance.now();current=Math.max(0,Math.min(DURATION,t));const state=draw({lines,world,type,footerLines,footerType,images,camera,music},current);if(state.video)await seekVideo(media,state.video,state.videoTime);post.begin();world.render(renderer,camera,width,height);images.render(renderer);lines.render(renderer,ortho,width,height);type.render(renderer);if(state.shot>=1&&state.shot<=11){post.footerScrim(1-ease((current-33.65)/.79));footerLines.render(renderer,ortho,width,height);footerType.render(renderer)}post.finish(current,beat(current-SONG_OFFSET,music)*.15);seek.value=current;select.value=shot(current);document.querySelector('#time').textContent=format(current)+' / '+format(DURATION);renderedFrames++;lastRenderMs=performance.now()-began}
function renderAt(t){let next=queue.catch(()=>undefined).then(()=>paint(t));queue=next.catch(()=>undefined);return next}
function format(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0')}
function pause(){playing=false;cancelAnimationFrame(frame);score.pause();play.textContent='Play'}
async function tick(){if(!playing||window.film.exporting)return;let t=score.paused?startFilm+(performance.now()-startWall)/1000:score.currentTime;try{await renderAt(t);if(current>=DURATION){pause();return}frame=requestAnimationFrame(tick)}catch(e){pause();status.textContent='Playback failed: '+e.message}}
play.onclick=async()=>{if(window.film.exporting)return;await ready;if(playing){pause();return}if(current>=DURATION)await renderAt(0);score.currentTime=current;startFilm=current;startWall=performance.now();playing=true;try{await score.play()}catch{}play.textContent='Pause';frame=requestAnimationFrame(tick)};seek.oninput=async()=>{if(window.film.exporting)return;pause();await ready;await renderAt(Number(seek.value))};shotNames.forEach((name,i)=>{let o=document.createElement('option');o.value=i;o.textContent=name;select.append(o)});select.onchange=async()=>{if(window.film.exporting)return;pause();await ready;await renderAt(boundaries[Number(select.value)])};document.querySelector('#mute').onclick=()=>{score.muted=!score.muted;document.querySelector('#mute').textContent=score.muted?'Unmute':'Mute';document.querySelector('#mute').setAttribute('aria-pressed',String(score.muted))};document.querySelector('#fullscreen').onclick=async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('#viewer').requestFullscreen()};
if(new URLSearchParams(location.search).get('export')==='1')document.body.classList.add('export-mode');window.film={ready,duration:DURATION,fps:30,canvas:renderer.domElement,renderAt,pause,exporting:false,setSize(w,h){width=w;height=h;renderer.setSize(w,h,false);post.setSize(w,h);images.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()},getState(){return {time:current,songTime:current-SONG_OFFSET,shot:shot(current),playing,ready:initialized,error,renderedFrames,lastRenderMs}}};
